### PR TITLE
Atlas 50 pipes

### PR DESCRIPTION
**Pull request by cryogenian**
[ch6225]

### CODE REVIEW

**Comment by rintcius** [comment]
@cryogenian I'm wondering if we should just leave errors like this unhandled. I mean it's valuable to know at compile time what query will be executed. But when we handle errors then the query can't be known at compile time anymore.

**Comment by cryogenian** [comment]
We can know this query looking at mongo logs 🙂 

In general I disagree that we should raise any error like this at all. We did as much as we could and we still are able to produce results, not producing them because we need more transparency isn't cool. As a user I would be angry in such situation.

**Comment by rintcius** [comment]
It may still be possible to return without error in cases like this,  e.g. by getting server info (not sure how or even if this is provided but good to find out).

We used to rely pretty heavily on the generated mongo plans, without needing the mongo logs. If we are going to need the logs for issues to find out what query exactly ran at the customer's site then that's definitely a step back.

Also, I'm curious to know if this specific error occurs with free plan only. If that's the case then I think it's not all that important, though if we can figure things out at compile time then that would be ideal.

**Comment by cryogenian** [comment]
I haven't found a command that shows the limit of aggregation pipeline length ¯\_(ツ)_/¯

This is the main thing about pushdown, right? We just do as much as we can and always falling back if we can't. We don't evaluate all pushdowns mandatory. 

BTW, yeah, this error could appear only on free plan of atlas.

**Comment by cryogenian** [comment]
Also we can implement sampling by just calling {$limit: 1} 51 times, but wouldnt it be the same thing?

**Pull request merged**
