### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by cryogenian**
This pr fixes scalar stages spec and also its in mimir (probably all of them, `disabled`, `light` and `full` return the same failure/error for me). 

[ch5964] [ch5983] 

#### Problems/bugs found

+ `$arrayElemAt` was used w/o checking that projection is actually array 
+ Mask filters worked incorrectly, mostly because they used to return `{uuid: null}` and this is incorrect because masking should preserve nulls
+ Pivot shouldn't return `[undefined, undefined]` in case of object pivoting, just `undefined` is enough (all those funny `cartouche0_pivot_undefined` things encountered because of this)
+ Not so important, but cartesian's temp fields should be namespaced
+ Project must preserve fields even if they are incorrect. 

#### What was done 

Because of cartesian semantics we need to preserve everything all the time, there is no way we can filter things by any normal value like `null`. This means that `Project`, `Mask` and `Pivot` have to work with something like `None` that works as a flag of nonexistence, the things a bit more complicated because we don't want to convert objects to array filter values and go back, so I added also projection that has no sense as `$ concat thatNonishThing`.

+ Introduced `missing` and `missingKey` as a concept of non-existent row and non-existent value in object.
+ Added typecheck to projection unfold (had to use `futu`), and removed `IndexedAccess` out of the code, because with `futu` it's redundant.
+ Fixed `Pivot`'s `missing` value behaviour
+ `Project` is evaluated step by step with filtering on every step by type and existence. `Project` returns `missing` if it fails.
+ Mask returns `missing` if it fails, I needed to switch the param by context of rebuilding mask, i.e. if we build child object use `missingKey` otherwise `missing`
+ Added `Presented` that filters `missing(state.uniqueKey)` and `Erase` that erases everything. Both are filtered during cartesian evaluation because we must preserve everything before multiplication.
+ Made `MaskSpec` a bit more verbose, it was difficult to actually understand what was going on there. 
+ Mask's type filters check only existence of field if the field has `ColumnType.Top` type set. 

#### Things that should be done, but I don't think that in this pr

+ `missing` probably should be an extension of `ExprF` like projection. 
+ temporary fields should be an extension of `ExprF`
+ `RWST` or other fancy monad instead of `MonadPlus` and uuid argument in pipeline compilation would be good.

### CODE REVIEW

**Comment by cryogenian** [comment]
Snapshot `4.3.3-97d0216`

**Comment by cryogenian** [comment]
+ `cart-22` and `cart-23` are fixed. (They didn't affect its and this is interesting)

Snapshot `4.3.3-3dbd731`

**Comment by cryogenian** [comment]
Ugh, I also think that having this `missing` key means that I need to remove `(un)focus[F]`, but it could wait until nested cartesian probably.

**Comment by alissapajer** [comment]
At this point our `ScalarStageSpec` are actually getting to be more comprehensive than our mimir integration tests! The `ScalarStageSpec` are written more systematically than the integration tests, so I think that's a big reason why they are catching things that the integration tests didn't catch.

**Comment by alissapajer** [comment]
[ch6080]

**Pull request merged**
