### PR TITLE
netty for ssl enabled connections

### PR DESCRIPTION
**Pull request by cryogenian**
It's also ridiculously slow on @beckyconning's atlas instance :-|

### CODE REVIEW

**Comment by cryogenian** [comment]
[ch3985]

**Comment by djspiewak** [comment]
@cryogenian FYI, we usually assign PRs rather than requesting reviews since review requests don’t show up in notifications. Whoever is assigned is responsible for approving and merging.

**Comment by wemrysi** [comment]
@cryogenian we're currently streaming one document at a time, if we added chunking it'd probably help quite a bit with performance.

**Comment by djspiewak** [comment]
@wemrysi @cryogenian Emrys' point is a really important one: chunking the documents is incredibly important. I didn't realize we weren't already doing this. I'll ticket it as it should represent an order of magnitude performance improvement for this datasource.

**Comment by cryogenian** [comment]
@djspiewak @wemrysi Yep, I've tried request 64 items initially, and it runs at least 4-10 times faster. But anyways much-much slower than mongo-cli. I hope here could be something else too 🙁

**Comment by djspiewak** [comment]
I would request something like 2048 items.

**Pull request merged**
