### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by cryogenian**
[ch5870] [ch5871]  

This depends on https://github.com/slamdata/quasar/pull/4101

Things added 

+ Added thing that works like `None` (kinda), a string constant that is produced based on `uniqueKey`. 
+ This constant is used to mark undefined in pivots and undefined parts of array in mask
+ Since those parts of array aren't null anymore added `$reduce` and `$concatArrays` operators binding
+ Split `NotNull` matcher into `PivotFilter` and `MaskFilter` both shouldn't conflict with existence of `null` in fields, because pivot is filtered by that constant, and mask is filtered by `{uuid: null}` 
+ Since pivoting returns special string instead of null in case of undefined values, pivot filter must check that result is either `undefined` or `[undefined, undefined]` --> `CustomPipe` is compiled down to `List[MongoPipe]`
+ Also added lots of `_id -> 0` in projects. Also since masking on `CPath.parse("_id") -> Set("String")` should return id `ColumnType.String` is interpreted as `List("string", "objectId")`
+ `MonadReader` in `Mask.rebuildTree`

### CODE REVIEW

**Comment by cryogenian** [comment]
Sorry about force pushes, I've mixed up quasar updates 🙁 

The build should pass after 120.1.1

**Comment by alissapajer** [comment]
:stop_sign: is up because @jsantos17 has found that more of mimir's integration tests are failing in this PR than on master. So we want to figure out what's up before merging this.

**Comment by jsantos17** [comment]
@alissapajer @cryogenian I have confirmed many tests are failing, both through the REPL and the REST API:

Case in point:

```
select b[*] + c[*] from `intArrays.data`
```

returns empty results. Setting `pushdownLevel` in the datasource configuration to `disabled` fixes it.

**Comment by cryogenian** [comment]
[ch5867] too

**Comment by alissapajer** [comment]
This fixes some known issues in mongo, so I'd like to land this before release on monday. @rintcius thoughts?

**Comment by rintcius** [comment]
@alissapajer sounds good!

**Pull request merged**
